// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn2t0ORuXQUgbfy9pTj_54Rf0Bch5cOtc',
    appId: '1:294569839134:web:8f257717f43be62d3efc0f',
    messagingSenderId: '294569839134',
    projectId: 'ayman-target-f0684',
    authDomain: 'ayman-target-f0684.firebaseapp.com',
    storageBucket: 'ayman-target-f0684.firebasestorage.app',
    measurementId: 'G-0Y8PQRBGZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKvApECieRZUIF4zVXaLaWZQJQOmf2JY',
    appId: '1:294569839134:android:5a229670541b89a93efc0f',
    messagingSenderId: '294569839134',
    projectId: 'ayman-target-f0684',
    storageBucket: 'ayman-target-f0684.firebasestorage.app',
    androidClientId: 'com.example.ayman_target',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdhXpN5X70LEOre1IPB_F5HiDp3_NOhI',
    appId: '1:294569839134:ios:92b74e13745f12473efc0f',
    messagingSenderId: '294569839134',
    projectId: 'ayman-target-f0684',
    storageBucket: 'ayman-target-f0684.firebasestorage.app',
    iosBundleId: 'com.example.aymanTarget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdhXpN5X70LEOre1IPB_F5HiDp3_NOhI',
    appId: '1:294569839134:ios:92b74e13745f12473efc0f',
    messagingSenderId: '294569839134',
    projectId: 'ayman-target-f0684',
    storageBucket: 'ayman-target-f0684.firebasestorage.app',
    iosBundleId: 'com.example.aymanTarget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn2t0ORuXQUgbfy9pTj_54Rf0Bch5cOtc',
    appId: '1:294569839134:web:5331eddae8c0e5eb3efc0f',
    messagingSenderId: '294569839134',
    projectId: 'ayman-target-f0684',
    authDomain: 'ayman-target-f0684.firebaseapp.com',
    storageBucket: 'ayman-target-f0684.firebasestorage.app',
    measurementId: 'G-T26C4ZJWZ2',
  );
}